apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: me
  name: me
spec:
  replicas: 1
  selector:
    matchLabels:
      app: me
  template:
    metadata:
      labels:
        app: me
    spec:
      containers:
        - image: ctrlmaniac/me
          imagePullPolicy: Always
          name: me
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
