apiVersion: v1
kind: Service
metadata:
  labels:
    app: me
  name: me
spec:
  ports:
    - name: 8001-8001
      port: 8001
      protocol: TCP
      targetPort: 8001
      nodePort: 31000
  selector:
    app: me
  type: NodePort
status:
  loadBalancer: {}
